### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#67] opened 2015-08-11 17:28 UTC
So sorry to do this, but is there anything we can do to make the countdown widget look better?

**Comment by Shorashim** [comment] 2015-08-11 17:29
![screen shot 2015-08-11 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/13404688/9204872/8b054cb4-4024-11e5-97ad-ad93c2c6e9fa.png)

**Comment by Shorashim** [comment] 2015-08-11 17:29
I think the text is weirdly centered and the actual countdown looks off and could look better if there is a way to do that. The text on the bottom of the widget is hard to read as well.

**Comment by IshaDakota** [comment] 2015-08-11 17:46
This is probably the best we can do within any reasonable timeframe - next step would be to build a countdown timer from scratch (weeks of devel).

<img width="991" alt="home___site-install" src="https://cloud.githubusercontent.com/assets/688507/9205286/dd42defe-4026-11e5-80d4-5dfee9d819e4.png">

**Comment by Shorashim** [comment] 2015-08-11 17:49
That's a little better. It should work for the launch

**Comment by IshaDakota** [comment] 2015-08-11 17:51
what does that mean? Do you want to design a new countdown timer?

**Comment by Shorashim** [comment] 2015-08-11 17:53
I don't think so. I need to wait until I show it to Michal to know anything for sure, but from this image it looks like it should work.

**Comment by IshaDakota** [comment] 2015-08-11 17:55
It's live on the site so you can check it out there

**Comment by Shorashim** [comment] 2015-08-11 18:05
Is it possible have it align properly on a larger screen? Do you see how it is off center? It also looks off center a bit on the normal size.

Additionally, is it possible to change the font on the bottom of the widget or no?

Thanks!

![screen shot 2015-08-11 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/13404688/9205704/61173a0c-4029-11e5-9d86-9f38ba1187b2.png)

**Comment by IshaDakota** [comment] 2015-08-11 18:09
look again, or refresh - that's the old version.

**Comment by Shorashim** [comment] 2015-08-11 18:53
Pasted the wrong thing, sorry. Still not looking right.

![screen shot 2015-08-11 at 1 03 05 pm](https://cloud.githubusercontent.com/assets/13404688/9206950/5ab3cd90-4030-11e5-8b62-fba38f28e63e.png)
![screen shot 2015-08-11 at 1 52 01 pm](https://cloud.githubusercontent.com/assets/13404688/9206954/61e3c39a-4030-11e5-8deb-a639a4f45c31.png)

**Comment by IshaDakota** [comment] 2015-08-11 19:15
what browser are you using? Working fine on my screen:

<img width="1431" alt="home___shorashim" src="https://cloud.githubusercontent.com/assets/688507/9207452/5b9f6bee-4033-11e5-8124-b97de83c63c9.png">

**Comment by Shorashim** [comment] 2015-08-11 19:20
Chrome. It's showing up really weird for some reason.

**Comment by IshaDakota** [comment] 2015-08-11 19:30
I just ran a cross browser test on dozens of different platforms and screens and it came up as designed in each:

http://app.crossbrowsertesting.com/public/iedc3a5e3d77208e/screenshots/zdd79cb992b9e37fbc9b

**Comment by Shorashim** [comment] 2015-08-11 19:37
So weird. Everything is showing up much differently for me.

**Comment by IshaDakota** [comment] 2015-08-11 22:03
you're going to need to figure out what the issue is with your computer or monitor... since I have a lot of screenshots that show consistence over many platforms, I am closing.

**Closed by IshaDakota** 2015-08-11 22:03 UTC
